Repository OSU-MC/Open-Response, pull requests merged in 2023-12, with the labels that each got.

#59 Repository Modernization
  client/package-lock.json
  client/package.json
Labels: dependencies

#38 Cleanup / Refactor Part 1
  .gitignore
  server/app/api/courses.js
  server/app/api/enrollments.js
  server/app/app.js
  server/app/server.js
  server/package-lock.json
  server/package.json
Labels: enhancement

#60 revise server read me
  server/README.md
Labels: documentation

#74 Release 0.0
  .gitignore
  client/package-lock.json
  client/package.json
  server/README.md
  server/app/api/courses.js
  server/app/api/enrollments.js
  server/app/app.js
  server/app/server.js
  server/package-lock.json
  server/package.json
Labels: documentation, dependencies, development
