Repository OSU-MC/Open-Response, pull requests merged in 2024-03, with the labels that each got.

#149 Optimized XSRF User Validation
  server/lib/auth.js
Labels: enhancement

#150 Move Project Documentation to GitHub Wiki
  API Endpoints MyClassroom.pdf
  README.md
  prd.md
  sda.md
  sdp.md
Labels: documentation

#155 Update Homepage and Remove Old Pages/Components
  client/src/old_components/LectureCard.js
  client/src/old_components/QuestionCard.js
  client/src/old_components/StudentGradebookColumns.js
  client/src/old_components/StudentLectureGradeColumns.js
  client/src/old_components/components.css
  client/src/old_pages/BasicTable.js
  client/src/old_pages/InstructorLectures.js
  client/src/old_pages/InstructorLiveLecture.js
  client/src/old_pages/InstructorRoster.js
  client/src/old_pages/InstructorStudentLanding.js
  client/src/old_pages/Instructor_Course.js
  client/src/old_pages/Instructor_Questions.js
  client/src/old_pages/StudentGradeBook.js
  client/src/old_pages/StudentGradeforSingleLecture.js
  client/src/old_pages/StudentLiveLecture.js
  client/src/old_pages/basicTable.css
  client/src/old_pages/data/InstructorProfileData.json
  client/src/old_pages/data/courseData.json
  client/src/old_pages/data/questionsData.json
  client/src/old_pages/data/studentGradebookData.json
  client/src/old_pages/data/studentGradebookNewData.json
  client/src/old_pages/data/studentLectureGrade.json
  client/src/old_pages/photos/logo.jpg
  client/src/old_pages/photos/sideBarButton.jpg
  client/src/old_pages/temp.css
  client/src/pages/Home.js
Labels: enhancement, development

#134 Teacher student prem
  client/src/components/JoinCourse.js
  client/src/hooks/useCourses.js
  client/src/pages/Landing.js
  client/src/pages/Signup.js
  client/src/pages/StudentLanding.js
  client/src/pages/TeacherLanding.js
  server/__tests__/app/api/courses.jest.js
  server/__tests__/app/api/lectures.jest.js
  server/__tests__/app/api/users.jest.js
  server/__tests__/app/models/enrollment.jest.js
  server/__tests__/app/models/user.jest.js
  server/__tests__/app/services/user_service.jest.js
  server/app/api/users.js
  server/app/models/user.js
  server/app/services/user_service.js
  server/db/migrations/20221223224326-create-users.js
  server/db/seeders/20221223225047-create-root-user.js
  server/db/seeders/20230202033013-add_api_test_data.js
Labels: enhancement

#167 Reduce dependencies
  client/package-lock.json
  client/package.json
  server/package-lock.json
  server/package.json
Labels: dependencies, development
