Repository OSU-MC/Open-Response, pull requests merged in 2025-05, with the labels that each got.

#314 fix formating issue
  client/src/pages/Lecture.jsx
Labels: development

#317 Baumanne/socket fix
  client/src/components/StudentGradebook.jsx
  client/src/components/TeacherGradebook.jsx
  client/src/hooks/useGrades.js
  client/src/hooks/useLectureQuestions.js
  client/src/hooks/useSectionId.js
  client/src/pages/Grades.jsx
  client/src/pages/Lectures.jsx
  client/src/styles/Grades.css
  core/app/api/grades.js
  core/app/services/course_service.js
  package.json
Labels: development

#318 Baumanne/course/section/lecture/questions
  client/src/components/AddLectureToSection.jsx
  client/src/components/QuestionCard.jsx
  client/src/components/StudentGradebook.jsx
  client/src/components/TeacherGradebook.jsx
  client/src/components/questions/SingleQuestionTeacher.jsx
  client/src/hooks/useGrades.js
  client/src/pages/Grades.jsx
  client/src/styles/Grades.css
  core/__tests__/app/api/enrollments.jest.js
  core/__tests__/app/api/grades.jest.js
  core/__tests__/app/api/lectureForSection.jest.js
  core/__tests__/app/api/responses.jest.js
  core/__tests__/app/models/response.jest.js
  core/app/api/grades.js
  core/app/api/lectureForSection.js
  core/app/api/questions.js
  core/app/api/questionsInLecture.js
  core/app/api/responses.js
  core/app/models/lecture.js
  core/app/models/lecture_for_section.js
  core/app/models/lecture_grade_weight.js
  core/app/models/question.js
  core/app/models/response.js
  core/app/services/question_service.js
  core/db/migrations/20250118235051-change-grading-attendance.js
  core/db/migrations/20250518-fix-lecturegradeweights-lectureforsectionid.js
  core/db/seeders/20230202033013-add_api_test_data.js
Labels: enhancement, development

#319 Sagedev - Teacher Past Lecture Prototype
  client/src/App.jsx
  client/src/components/LectureCard.jsx
  client/src/pages/PastLectureId.jsx
  client/src/styles/index.css
  package-lock.json
  package.json
Labels: enhancement

#324 Baumanne/documentation
  client/src/components/StudentGradebook.jsx
  client/src/components/TeacherGradebook.jsx
  client/src/hooks/useGrades.js
  client/src/hooks/useLectureForSectionQuestions.js
  client/src/hooks/useSectionId.js
  client/src/pages/Lectures.jsx
Labels: documentation

#326 Add setup scripts for Docker, Improve NPM Run Scripts
  docker/first_time_setup.sh
  package.json
  socket/package.json
Labels: documentation, enhancement, development
