Repository OSU-MC/Open-Response, pull requests merged in 2025-03, with the labels that each got.

#301 Remove mentions of MyClassroom and replace with Open-Response
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
  client/README.md
  client/package.json
  client/websocket/README.md
  core/.jest/setEnvVars.js
  core/README.md
  core/__tests__/app/api/courses.jest.js
  core/__tests__/app/api/enrollments.jest.js
  core/__tests__/app/api/grades.jest.js
  core/__tests__/app/api/lectureForSection.jest.js
  core/__tests__/app/api/lectureSummaries.jest.js
  core/__tests__/app/api/lectures.jest.js
  core/__tests__/app/api/questions.jest.js
  core/__tests__/app/api/questionsInLecture.jest.js
  core/__tests__/app/api/responses.jest.js
  core/__tests__/app/api/sections.jest.js
  core/__tests__/app/api/users.jest.js
  core/__tests__/app/models/enrollment.jest.js
  core/__tests__/app/models/grades.jest.js
  core/__tests__/app/models/response.jest.js
  core/__tests__/app/models/session.jest.js
  core/__tests__/app/models/user.jest.js
  core/__tests__/app/services/user_service.jest.js
  core/compose.yml
  core/config/db.config.js
  core/db/init.sql
  core/db/seeders/20221223225047-create-root-user.js
  core/db/seeders/20230202033013-add_api_test_data.js
  core/lib/auth.js
  core/lib/mailer.js
  core/notif/README.md
  core/package-lock.json
  core/package.json
  core/postman/collections/Users.json
  core/postman/env.json
  core/redis/README.md
  package-lock.json
  package.json
Labels: documentation, enhancement, dependencies

#300 Merge woodnath/deployment
  DEPLOYMENT.md
  package-lock.json
  package.json
  vhost.conf
Labels: documentation, dependencies, development

#302 Add QOL Script for resetting database
  core/README.md
Labels: documentation

#303 Containerize all Services & Orchestrate with Docker Swarm
  .gitignore
  DEPLOYMENT.md
  ORCHESTRATION.md
  client/.dockerignore
  client/Dockerfile
  client/nginx.conf
  client/src/index.jsx
  client/vite.config.js
  config/config.json
  core/.env.example
  core/Dockerfile
  core/app/app.js
  core/app/core.js
  core/compose.yml
  core/entrypoint.sh
  core/package.json
  docker-stack.yml
  docker_swarm_scaling.py
  package-lock.json
  package.json
Labels: documentation, enhancement, dependencies, development

#307 Landing
  client/package.json
  client/src/components/AddLecture.jsx
  client/src/components/JoinCourse.jsx
  client/src/pages/Lectures.jsx
  client/src/pages/StudentLanding.jsx
  client/src/pages/TeacherLanding.jsx
  client/src/styles/index.css
  client/src/styles/landing.css
  core/README.md
  core/package.json
  package-lock.json
Labels: enhancement, development

#306 Merge woodnath/actions
  .github/workflows/client.yml
  .github/workflows/core.yml
  client/package.json
  package-lock.json
Labels: enhancement, development, security

#308 Baumanne/courses/section instructor
  client/src/components/nav/Navigation.jsx
  client/src/components/nav/Tabs.jsx
  client/src/pages/Lectures.jsx
  client/src/pages/Sections.jsx
  client/src/styles/Section.css
  client/src/styles/landing.css
Labels: bug, enhancement

#309 Quick patches prior to the Project Partner Meeting
  ORCHESTRATION.md
  client/src/pages/Lectures.jsx
  docker-stack.yml
  package-lock.json
Labels: bug, documentation, dependencies, development

#310 Update .env.example to remove `MyClassroom` reference
  client/.env.example
Labels: good first issue, development
